name: test
on: [push]
permissions:
  contents: read
  checks: write
jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.3'
      - run: go version
      - run: go mod download
      - run: go build cmd/astronomer.go
  go-vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.3'
      - run: go version
      - run: go mod download
      - run: go vet ./...
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          args: --timeout 300s
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.3'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Run tests
        run: go test -coverprofile coverage.txt -v ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.3.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: QuokkaStake/astronomer
  migrations:
    name: migrations
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.3'
      - run: go build cmd/astronomer.go
      - run: ./astronomer migrate --config assets/config-ci.toml
      - run: ./astronomer rollback --config assets/config-ci.toml
      - run: ./astronomer migrate --config assets/config-ci.toml
